# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file


# Azure Monitor Exporter Configuration

exporters:
  azuremonitor:
    endpoint: "https://dc.services.visualstudio.com/v2/track" # AzMon Default
    instrumentation_key: "80fe2786-859b-4617-acf6-57b9e0e64392" # My AzMon

    
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor, spanmetrics]