# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file


# OTLP Exporter Configuration for Internal Backend

exporters:
  otlp:
    endpoint: "http://localhost:4317"
    tls:
      insecure: true
      insecure_skip_verify: true


service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, spanmetrics]