# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file


# OTLP Exporter Configuration for Internal Backend

# Using default receivers in otelcol-config.yml  

exporters:
  otlp:
    endpoint: "localhost:4319"
#    endpoint: "https://test1.diagnostics.monitoring.core.windows.net/"
  logging:
    endpoint: "localhost:4319"
#    endpoint: "https://test1.diagnostics.monitoring.core.windows.net/"