# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file


# OTLP Exporter Configuration for Internal Backend

exporters:
  otlp:
#    endpoint: "10.0.0.4:4317" # vm eth0
    endpoint: "172.17.0.1:4317" #vm docker0